'use client';

import { useState, useEffect } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { api, Script } from '@/lib/api';
import SubtitleViewer from '@/components/SubtitleViewer';

export default function SubsPage() {
  const params = useParams();
  const scriptId = params.id as string;

  const [script, setScript] = useState<Script | null>(null);
  const [srt, setSrt] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    async function load() {
      try {
        const s = await api.scripts.get(scriptId);
        setScript(s);

        if (s.transcription) {
          const srtData = await api.transcription.getSRT(scriptId);
          setSrt(srtData.srt);
        }
      } catch (err: unknown) {
        setError(err instanceof Error ? err.message : 'Failed to load subtitles');
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [scriptId]);

  if (loading) {
    return <div style={{ padding: '2rem', color: 'var(--text-muted)' }}>Loading...</div>;
  }

  return (
    <div style={{ maxWidth: '860px' }}>
      <a
        href={`/scripts/${scriptId}/voice`}
        style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textDecoration: 'none' }}
      >
        ← Back to voice
      </a>

      <div style={{ margin: '0.75rem 0 2rem' }}>
        <h1 style={{ margin: 0, fontSize: '1.4rem' }}>Subtitles</h1>
        <p style={{ margin: '0.25rem 0 0', color: 'var(--text-muted)', fontSize: '0.875rem' }}>
          {script?.topic}
        </p>
      </div>

      {error && (
        <div
          style={{
            padding: '0.75rem 1rem',
            background: 'rgba(239,68,68,0.1)',
            border: '1px solid rgba(239,68,68,0.3)',
            borderRadius: '6px',
            color: 'var(--danger)',
            fontSize: '0.875rem',
            marginBottom: '1rem',
          }}
        >
          {error}
        </div>
      )}

      {!script?.transcription ? (
        <div className="card" style={{ textAlign: 'center', padding: '3rem 2rem' }}>
          <p style={{ margin: '0 0 0.5rem', fontSize: '1rem' }}>No transcription yet</p>
          <p style={{ color: 'var(--text-muted)', marginBottom: '1.5rem', fontSize: '0.875rem' }}>
            Generate voice and transcribe audio first.
          </p>
          <Link href={`/scripts/${scriptId}/voice`} className="btn btn-primary">
            Go to Voice Generation →
          </Link>
        </div>
      ) : !srt ? (
        <div className="card" style={{ color: 'var(--text-muted)', fontSize: '0.875rem' }}>
          Could not load SRT file.
        </div>
      ) : (
        <div className="card">
          <div style={{ marginBottom: '1rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '0.5rem' }}>
            <div>
              <h2 style={{ margin: 0, fontSize: '1rem' }}>Subtitle Blocks</h2>
              <p style={{ margin: '0.2rem 0 0', fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                Generated by Deepgram nova-2 · word-level timestamps
              </p>
            </div>
          </div>
          <SubtitleViewer
            srt={srt}
            rawJson={script.transcription?.raw_json as object}
          />
        </div>
      )}
    </div>
  );
}
